//----------------------------------------------------------------
//
//  4190.307 Operating Systems (Spring 2026)
//
//  Project #2: System calls
//
//  March 19, 2026
//
//  Jin-Soo Kim (jinsoo.kim@snu.ac.kr)
//  Systems Software & Architecture Laboratory
//  Dept. of Computer Science and Engineering
//  Seoul National University
//
//----------------------------------------------------------------

.globl machinevec
.align 4
machinevec:
        # M-mode code here
       


